/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/student/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Students
		 * @description Retrieve all students and their class assignments from the `student` and `studentclassassociation` tables.
		 *
		 *     - If the user is a **student**, only their own record is returned.
		 *     - If the user is a **teacher** or **admin**, all students are returned with class association.
		 */
		get: operations['get_students_student__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/student/{sid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Student By Id
		 * @description Retrieve a specific student by SID from the `student` and `studentclassassociation` tables.
		 *
		 *     - If the user is a **student**, their own SID must be used.
		 *     - If the user is a **teacher** or **admin**, the SID of any student must be provided.
		 *
		 *     Returns the student’s personal information and class association.
		 */
		get: operations['get_student_by_id_student__sid__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/teacher/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Teachers
		 * @description Retrieve all teachers from the `teacher` table.
		 *
		 *     - Available to users with roles **Admin** and **Teacher**.
		 *     - Teachers can view the full list of teachers (e.g., for scheduling or contact purposes).
		 */
		get: operations['get_teachers_teacher__get'];
		/**
		 * Update Areaofexpertise
		 * @description Update the area of expertise of a teacher.
		 */
		put: operations['update_areaOfExpertise_teacher__put'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/teacher/{tid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Teacher By Id
		 * @description Retrieve a specific teacher by TID from the `teacher` table.
		 *
		 *     - If the user is a **teacher** or **admin**, they may specify any TID.
		 */
		get: operations['get_teacher_by_id_teacher__tid__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/token': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Login */
		post: operations['login_token_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/refresh': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Refresh Token */
		post: operations['refresh_token_refresh_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/protected/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Protected */
		get: operations['protected_protected__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/hour/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get All Teacher Hours
		 * @description Retrieve all entries from the `indyhour` table, joined with the `teacher` table and
		 *     `HourToTeacherAreaOfExpertiseAssociation` to include full teacher name and area of expertise.
		 *
		 *     The data is aggregated by (day, hour, teacher) and returned with optional expertise labels.
		 */
		get: operations['get_all_teacher_hours_hour__get'];
		put?: never;
		/**
		 * Create Hour Entry As Teacher
		 * @description Create a new `indyhour` entry as a logged-in teacher.
		 *
		 *     - Requires Teacher role.
		 *     - Uses the teacher's ID from the JWT token.
		 *     - Fails if indySheetChangeAble is disabled in the `config` table.
		 *     - Fails if the teacher is not found in the `teacher` table.
		 */
		post: operations['create_hour_entry_as_teacher_hour__post'];
		/** Delete Hour As Teacher */
		delete: operations['delete_hour_as_teacher_hour__delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/hour/admin': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create Hour Entry As Admin
		 * @description Create a new `indyhour` entry on behalf of a teacher as an Admin.
		 *
		 *     - Requires Admin role.
		 *     - Teacher ID must be explicitly provided in the URL path.
		 *     - Fails if the teacher does not exist in the `teacher` table.
		 */
		post: operations['create_hour_entry_as_admin_hour_admin_post'];
		/** Delete Hour As Admin */
		delete: operations['delete_hour_as_admin_hour_admin_delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/hour/{teacher}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Hours Per Teacher */
		get: operations['get_hours_per_teacher_hour__teacher__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Entries
		 * @description Retrieve all entries for the authenticated student.
		 *
		 *     - Role: Schueler (Student)
		 *     - Retrieves entries from the `entry` table based on the student's own ID.
		 */
		get: operations['get_entries_entry__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/{sid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Entries For Student
		 * @description Retrieve all entries for a specific student by SID.
		 *
		 *     - Role: Admin only
		 *     - Returns entries from the `entry` table for the given student ID.
		 */
		get: operations['get_entries_for_student_entry__sid__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/date/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Entries By Date
		 * @description Retrieve all entries for a given student and IndY date, grouped by hour and entry type.
		 *
		 *     - If the user is a student, `sid` is automatically set to their ID.
		 *     - Validates the provided date as an official IndY day.
		 *     - Aggregates entries from the tables: `entrynormal`, `entryschoolevent`, `entryabsence`, and `entryfreeroom`.
		 *     - Results are grouped by hour (3 and 4).
		 */
		get: operations['get_entries_by_date_entry_date__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/normal/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get All Entrynormal Entries
		 * @description Retrieve all normal entries in the system.
		 *
		 *     - Roles: Admin and Teacher
		 *     - Returns all entries from the `entrynormal` table.
		 */
		get: operations['get_all_entrynormal_entries_entry_normal__get'];
		put?: never;
		/**
		 * Add Entrynormal
		 * @description Create a new normal entry for the authenticated student.
		 *
		 *     - Role: Schueler (Student)
		 *     - Validates that the entry date is not in the past.
		 *     - Checks teacher availability for the given hour and day.
		 *     - Ensures the student limit for the teacher/hour is not exceeded.
		 *     - Calls a function to create a general entry record.
		 */
		post: operations['add_entrynormal_entry_normal__post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/normal/today': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get All Entrynormal For Today
		 * @description Retrieve all `entrynormal` entries for today.
		 *
		 *     - Roles: Admin and Teacher
		 *     - Includes the student’s class info from `studentclassassociation`.
		 */
		get: operations['get_all_entrynormal_for_today_entry_normal_today_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/normal/{sid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Entriesnormal By Sid
		 * @description Retrieve all normal entries for a specific student.
		 *
		 *     - Role: Schueler (only for their own sid) or Admin/Teacher (any sid)
		 *     - Returns all `entrynormal` records for the given student ID.
		 */
		get: operations['get_entriesnormal_by_sid_entry_normal__sid__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/freeroom/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get All Entryfreeroom Entries
		 * @description Retrieve all entries from the `entryfreeroom` table.
		 *
		 *     - Accessible to **Admins** and **Teachers**.
		 *     - Returns a complete list of free room entries for all students.
		 */
		get: operations['get_all_entryfreeroom_entries_entry_freeroom__get'];
		put?: never;
		/**
		 * Add Entryfreeroom
		 * @description Create a new free room entry for the authenticated student.
		 *
		 *     - Role: Schueler (Student)
		 *     - Calls the general `add_entry` function to create a base entry record.
		 *     - Adds additional details specific to free room entries (subject, house, floor, activity).
		 */
		post: operations['add_entryfreeroom_entry_freeroom__post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/freeroom/today': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get All Entryfreeroom For Today
		 * @description Retrieve all free room entries for today.
		 *
		 *     - Roles: Admin and Teacher
		 *     - Includes student class information from `studentclassassociation`.
		 */
		get: operations['get_all_entryfreeroom_for_today_entry_freeroom_today_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/freeroom/{sid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Entriesfreeroom By Sid
		 * @description Retrieve all free room entries for a specific student.
		 *
		 *     - Role: Schueler (only for their own sid) or Admin/Teacher (any sid)
		 *     - Returns all `entryfreeroom` records for the given student ID.
		 */
		get: operations['get_entriesfreeroom_by_sid_entry_freeroom__sid__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/absence/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get All Entryabsence Entries
		 * @description Retrieve all entries from the `entryabsence` table.
		 *
		 *     - Accessible to **Admins** and **Teachers**.
		 *     - Returns all absence entries for all students.
		 */
		get: operations['get_all_entryabsence_entries_entry_absence__get'];
		put?: never;
		/**
		 * Add Entryabsence
		 * @description Create a new absence entry for the authenticated student.
		 *
		 *     - Role: Schueler (Student)
		 *     - Calls the shared `add_entry` function with the absence flag.
		 *     - Sets `entryPastPresent` flag based on whether the absence date is in the future.
		 */
		post: operations['add_entryabsence_entry_absence__post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/absence/today': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get All Entryabsence For Today
		 * @description Retrieve all absence entries for today.
		 *
		 *     - Roles: Admin and Teacher
		 *     - Includes student class info from `studentclassassociation`.
		 */
		get: operations['get_all_entryabsence_for_today_entry_absence_today_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/absence/{sid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Entriesabsence By Sid
		 * @description Retrieve all absence entries for a specific student by SID.
		 *
		 *     - Returns all absence records for the given student ID.
		 *     - Students must provide their own sid.
		 */
		get: operations['get_entriesabsence_by_sid_entry_absence__sid__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/schoolevent/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get All Schoolevent Entries
		 * @description Retrieve all entries from the `entryschoolevent` table.
		 *
		 *     - Accessible to **Admins** and **Teachers**.
		 *     - Returns a full list of school event entries.
		 */
		get: operations['get_all_schoolevent_entries_entry_schoolevent__get'];
		put?: never;
		/**
		 * Add Entryschoolevent
		 * @description Create a new school event entry for the authenticated student.
		 *
		 *     - Role: Schueler (Student)
		 *     - Calls the shared `add_entry` function.
		 *     - Adds additional info like `tid` (teacher id) and optional `description`.
		 */
		post: operations['add_entryschoolevent_entry_schoolevent__post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/schoolevent/today': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get All Entryschoolevent For Today
		 * @description Retrieve all school event entries for today.
		 *
		 *     - Roles: Admin and Teacher
		 *     - Includes related class info from `studentclassassociation`.
		 */
		get: operations['get_all_entryschoolevent_for_today_entry_schoolevent_today_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/schoolevent/{sid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Entriesschoolevent By Sid
		 * @description Retrieve all school event entries for a specific student by SID.
		 *
		 *     - Role: Schueler can only access their own entries.
		 *     - Returns entries from `entryschoolevent` for the given student.
		 */
		get: operations['get_entriesschoolevent_by_sid_entry_schoolevent__sid__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/validdays/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Valid Days
		 * @description Retrieve all valid IndY days between two dates.
		 *
		 *     - Valid days are Mondays, Wednesdays, and Fridays that pass IndY validation.
		 *     - Returns a list of date + weekday name.
		 */
		get: operations['get_valid_days_validdays__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/validdays/status/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Valid Days With Status
		 * @description Retrieve all valid IndY days between two dates including the student's status on each day.
		 *
		 *     - **Role**: `Schueler` (Student)
		 *     - Each returned date includes weekday name and student's status (e.g., entry type or "No entries found").
		 */
		get: operations['get_valid_days_with_status_validdays_status__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/specialindy/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Special Indy
		 * @description Retrieve all SpecialIndy sessions for a given date.
		 *
		 *     - A `SpecialIndy` is a subject-specific or custom session offered on selected days by teachers.
		 */
		get: operations['get_special_indy_specialindy__get'];
		put?: never;
		/**
		 * Create Special Indy As Teacher
		 * @description Create a SpecialIndy session for multiple dates as a teacher.
		 *
		 *     - Requires active configuration to allow changes.
		 *     - Replaces existing `specialindy`, `entrynormal`, and `entry` records for the same time slot.
		 *     - Only users with role `Teacher` or `Admin` can use this endpoint.
		 */
		post: operations['create_special_indy_as_teacher_specialindy__post'];
		/** Delete Special Indy Teacher */
		delete: operations['delete_special_indy_teacher_specialindy__delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/specialindy/{tid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create Special Indy As Admin
		 * @description Admin-only endpoint to create a SpecialIndy session for a specific teacher.
		 *
		 *     - Used when an Admin needs to set up sessions on behalf of a teacher.
		 *     - Requires teacher ID in path.
		 *     - Automatically cleans up overlapping `entrynormal` and `entry` records.
		 */
		post: operations['create_special_indy_as_admin_specialindy__tid__post'];
		/** Delete Special Indy Admin */
		delete: operations['delete_special_indy_admin_specialindy__tid__delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/studentcount/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Student Count
		 * @description Returns the number of students assigned to each teacher for every hour on a specific IndY day.
		 *
		 *     - Counts are based on `entrynormal` and `entryspecial` records.
		 *     - Missing combinations (teacher + hour) will be returned with a student count of 0.
		 */
		get: operations['student_count_studentcount__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/subject/active': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Active Subjects
		 * @description Retrieve all active subjects (active = 1) from the `subject` table.
		 */
		get: operations['get_active_subjects_subject_active_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/missing/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Missing Entries
		 * @description Retrieve all missing indy entries for the currently logged-in student.
		 *
		 *     - Requires the user to be authenticated as a `Schueler` (student).
		 *     - Returns a list of date and hour pairs where the student has no Indy entries.
		 */
		get: operations['get_missing_entries_missing__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/missing/{sid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Missing Entries By Id
		 * @description Retrieve missing Indy entries for a specific student ID.
		 *
		 *     - Admins can use this to view missing entries for any student.
		 *     - Students can only request their **own** data.
		 *     - Raises 403 if a student attempts to access another student's data.
		 */
		get: operations['get_missing_entries_by_id_missing__sid__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/sign/{sid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Sign */
		post: operations['sign_sign__sid__post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/sign/normal': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Hours Normal */
		get: operations['get_hours_normal_sign_normal_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/sign/event': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Hours Schoolevent */
		get: operations['get_hours_schoolevent_sign_event_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/sign/special': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Hours Specialindy */
		get: operations['get_hours_specialIndy_sign_special_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/sign/all/normal': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get All Normal */
		get: operations['get_all_normal_sign_all_normal_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/kv/class': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Class Kv */
		get: operations['get_class_kv_kv_class_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/kv/sign/normal': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Hours Normal Not Signed As Kv */
		get: operations['get_hours_normal_not_signed_as_kv_kv_sign_normal_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/kv/sign/event': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Hours Not Signed Event As Kv */
		get: operations['get_hours_not_signed_event_as_kv_kv_sign_event_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/kv/sign/special': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Hours Not Signed Special As Kv */
		get: operations['get_hours_not_signed_special_as_kv_kv_sign_special_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/kv/sign/absence': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Hours Not Signed Absence As Kv */
		get: operations['get_hours_not_signed_absence_as_kv_kv_sign_absence_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/kv/sign/freeroom': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Hours Free Room As Kv */
		get: operations['get_hours_free_room_as_kv_kv_sign_freeroom_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/kv/missing': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Missing Entries As Kv */
		get: operations['get_missing_entries_as_kv_kv_missing_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/kv/{sid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Sign */
		post: operations['sign_kv__sid__post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/kv/statistics': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Statistics */
		get: operations['get_statistics_kv_statistics_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/report/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Own Report
		 * @description Retrieve the IndY report for the currently logged-in student.
		 *
		 *     - **Role**: `Schueler` (Student)
		 *     - Returns a list of all recorded IndY entries including date, hour, subject, etc.
		 *     - Also includes statistics such as total entered hours, total possible hours, absences, and subject distribution.
		 */
		get: operations['get_own_report_entry_report__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/report/{sid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Report For Student
		 * @description Retrieve the IndY report for a specific student.
		 *
		 *     - **Role**: `Teacher` or `Admin`
		 *     - A Student has to provide his own **sid**.
		 *     - Requires a valid `sid` (student ID) as path parameter.
		 *     - Returns a comprehensive list of the student's entries and associated statistics.
		 */
		get: operations['get_report_for_student_entry_report__sid__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/rooms/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get All Rooms
		 * @description Get a list of all rooms.
		 *
		 *     - Returns all room entries from the `Room` table.
		 */
		get: operations['get_all_rooms_rooms__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/rooms/available': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Available Rooms
		 * @description Get a list of rooms that are currently available (not booked) for a specific date.
		 *
		 *     - Role: Teacher or Admin required
		 *     - Checks room usage in the `indyhour` and `specialIndy` tables.
		 *     - Returns a filtered list of `Room` entries that are not in use on the given date.
		 *     - Defaults to today's date if no date is provided.
		 */
		get: operations['get_available_rooms_rooms_available_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/house/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Houses
		 * @description Returns all `house IDs`.
		 */
		get: operations['get_houses_house__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/floor/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Floors
		 * @description Returns all `floor IDs`.
		 */
		get: operations['get_floors_floor__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/untis/students/load': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Load And Save Students
		 * @description Loading students from untis and saving them to the database
		 */
		post: operations['load_and_save_students_untis_students_load_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/untis/subjects/load': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Load And Save Subjects
		 * @description Lädt Fächer aus Untis und speichert sie in die DB
		 */
		post: operations['load_and_save_subjects_untis_subjects_load_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/untis/classes/load': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Load And Save Classes
		 * @description Lädt Klassen des aktuellen Schuljahres aus Untis und speichert sie in die DB
		 */
		post: operations['load_and_save_classes_untis_classes_load_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/untis/classesassociations/load': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Load And Save Classes Associations
		 * @description Lädt Klassen des aktuellen Schuljahres aus Untis und speichert sie in die DB
		 */
		post: operations['load_and_save_classes_associations_untis_classesassociations_load_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/untis/schoolyears/load': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Load And Save Schoolyears
		 * @description Lädt alle Schuljahre aus Untis und speichert sie in die DB
		 */
		post: operations['load_and_save_schoolyears_untis_schoolyears_load_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/untis/teachers/load': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Load And Save Teachers
		 * @description Lädt Lehrer aus Untis
		 */
		post: operations['load_and_save_teachers_untis_teachers_load_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/untis/holidays/load': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Load And Save Holidays */
		post: operations['load_and_save_holidays_untis_holidays_load_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/teacher/absences/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Teacher Absences
		 * @description Retrieve all teacher absences from the `teacherindyhourcancellations` table.
		 *
		 *     - Available to users with roles **Admin** , **Teacher** and **Schueler**.
		 *     - Returns a list starting from the current date.
		 */
		get: operations['get_teacher_absences_teacher_absences__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/special/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get All Special Entries
		 * @description Retrieve all normal entries in the system.
		 *
		 *     - Roles: Admin and Teacher
		 *     - Returns all entries from the `entrynormal` table.
		 */
		get: operations['get_all_special_entries_entry_special__get'];
		put?: never;
		/**
		 * Add Entryspecial
		 * @description Create a new special indy entry for the authenticated student.
		 *
		 *     - Role: Schueler (Student)
		 *     - Validates that the entry date is not in the past.
		 *     - Checks teacher availability for the given hour and day.
		 *     - Ensures the student limit for the teacher/hour is not exceeded.
		 *     - Calls a function to create a general entry record.
		 */
		post: operations['add_entryspecial_entry_special__post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/special/today': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get All Special For Today
		 * @description Retrieve all `entrynormal` entries for today.
		 *
		 *     - Roles: Admin and Teacher
		 *     - Includes the student’s class info from `studentclassassociation`.
		 */
		get: operations['get_all_special_for_today_entry_special_today_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entry/special/{sid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Entryspecial By Sid
		 * @description Retrieve all normal entries for a specific student.
		 *
		 *     - Role: Schueler (only for their own sid) or Admin/Teacher (any sid)
		 *     - Returns all `entrynormal` records for the given student ID.
		 */
		get: operations['get_entryspecial_by_sid_entry_special__sid__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Root */
		get: operations['root__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** Body_login_token_post */
		Body_login_token_post: {
			/** Grant Type */
			grant_type?: string | null;
			/** Username */
			username: string;
			/** Password */
			password: string;
			/**
			 * Scope
			 * @default
			 */
			scope: string;
			/** Client Id */
			client_id?: string | null;
			/** Client Secret */
			client_secret?: string | null;
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components['schemas']['ValidationError'][];
		};
		/** RefreshRequest */
		RefreshRequest: {
			/** Refresh Token */
			refresh_token: string;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	get_students_student__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_student_by_id_student__sid__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				sid: number | null;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_teachers_teacher__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	update_areaOfExpertise_teacher__put: {
		parameters: {
			query: {
				areaOfExpertise: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_teacher_by_id_teacher__tid__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				tid: string | null;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	login_token_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/x-www-form-urlencoded': components['schemas']['Body_login_token_post'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	refresh_token_refresh_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RefreshRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	protected_protected__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	get_all_teacher_hours_hour__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	create_hour_entry_as_teacher_hour__post: {
		parameters: {
			query: {
				day: string;
				hour: number;
				room: string;
				consultation: boolean;
				slimit: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	delete_hour_as_teacher_hour__delete: {
		parameters: {
			query: {
				day: string;
				hour: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_hour_entry_as_admin_hour_admin_post: {
		parameters: {
			query: {
				teacher: string;
				day: string;
				hour: number;
				room: string;
				consultation: boolean;
				slimit?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	delete_hour_as_admin_hour_admin_delete: {
		parameters: {
			query: {
				teacher: string;
				day: string;
				hour: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_hours_per_teacher_hour__teacher__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				teacher: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_entries_entry__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_entries_for_student_entry__sid__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				sid: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_entries_by_date_entry_date__get: {
		parameters: {
			query: {
				indy_date: string;
				sid?: number | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_all_entrynormal_entries_entry_normal__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	add_entrynormal_entry_normal__post: {
		parameters: {
			query: {
				indy_date: string;
				hour: number;
				tid: string;
				subject: string;
				activity?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_all_entrynormal_for_today_entry_normal_today_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_entriesnormal_by_sid_entry_normal__sid__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				sid: number | null;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_all_entryfreeroom_entries_entry_freeroom__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	add_entryfreeroom_entry_freeroom__post: {
		parameters: {
			query: {
				indy_date: string;
				hour: number;
				subject: string;
				house: string;
				floor: string;
				activity?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_all_entryfreeroom_for_today_entry_freeroom_today_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_entriesfreeroom_by_sid_entry_freeroom__sid__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				sid: number | null;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_all_entryabsence_entries_entry_absence__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	add_entryabsence_entry_absence__post: {
		parameters: {
			query: {
				indy_date: string;
				hour: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_all_entryabsence_for_today_entry_absence_today_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_entriesabsence_by_sid_entry_absence__sid__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				sid: number | null;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_all_schoolevent_entries_entry_schoolevent__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	add_entryschoolevent_entry_schoolevent__post: {
		parameters: {
			query: {
				indy_date: string;
				hour: number;
				tid: string;
				description?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_all_entryschoolevent_for_today_entry_schoolevent_today_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_entriesschoolevent_by_sid_entry_schoolevent__sid__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				sid: number | null;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_valid_days_validdays__get: {
		parameters: {
			query: {
				start_date: string;
				end_date: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_valid_days_with_status_validdays_status__get: {
		parameters: {
			query: {
				start_date: string;
				end_date: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_special_indy_specialindy__get: {
		parameters: {
			query?: {
				start_date?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_special_indy_as_teacher_specialindy__post: {
		parameters: {
			query: {
				day: string;
				hour: number;
				startDate: string;
				endDate: string;
				specialAreaOfExpertise: string;
				slimit: number;
				room: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	delete_special_indy_teacher_specialindy__delete: {
		parameters: {
			query: {
				day: string;
				hour: number;
				startdate: string;
				enddate: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_special_indy_as_admin_specialindy__tid__post: {
		parameters: {
			query: {
				day: string;
				hour: number;
				startDate: string;
				endDate: string;
				specialAreaOfExpertise: string;
				slimit: number;
				room: string;
			};
			header?: never;
			path: {
				tid: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	delete_special_indy_admin_specialindy__tid__delete: {
		parameters: {
			query: {
				day: string;
				hour: number;
				startdate: string;
				enddate: string;
			};
			header?: never;
			path: {
				tid: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	student_count_studentcount__get: {
		parameters: {
			query: {
				indy_date: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_active_subjects_subject_active_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_missing_entries_missing__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_missing_entries_by_id_missing__sid__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				sid: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	sign_sign__sid__post: {
		parameters: {
			query: {
				anwesend: boolean;
				indy_date: string;
				hour: number;
				tid: string;
			};
			header?: never;
			path: {
				sid: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_hours_normal_sign_normal_get: {
		parameters: {
			query: {
				tid: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_hours_schoolevent_sign_event_get: {
		parameters: {
			query: {
				tid: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_hours_specialIndy_sign_special_get: {
		parameters: {
			query: {
				tid: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_all_normal_sign_all_normal_get: {
		parameters: {
			query: {
				tid: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_class_kv_kv_class_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_hours_normal_not_signed_as_kv_kv_sign_normal_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_hours_not_signed_event_as_kv_kv_sign_event_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_hours_not_signed_special_as_kv_kv_sign_special_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_hours_not_signed_absence_as_kv_kv_sign_absence_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_hours_free_room_as_kv_kv_sign_freeroom_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_missing_entries_as_kv_kv_missing_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	sign_kv__sid__post: {
		parameters: {
			query: {
				anwesend: boolean;
				indy_date: string;
				hour: number;
			};
			header?: never;
			path: {
				sid: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_statistics_kv_statistics_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_own_report_entry_report__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	get_report_for_student_entry_report__sid__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				sid: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_all_rooms_rooms__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_available_rooms_rooms_available_get: {
		parameters: {
			query?: {
				check_date?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_houses_house__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_floors_floor__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	load_and_save_students_untis_students_load_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	load_and_save_subjects_untis_subjects_load_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	load_and_save_classes_untis_classes_load_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	load_and_save_classes_associations_untis_classesassociations_load_post: {
		parameters: {
			query: {
				indy_date: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	load_and_save_schoolyears_untis_schoolyears_load_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	load_and_save_teachers_untis_teachers_load_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	load_and_save_holidays_untis_holidays_load_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	get_teacher_absences_teacher_absences__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_all_special_entries_entry_special__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	add_entryspecial_entry_special__post: {
		parameters: {
			query: {
				indy_date: string;
				hour: number;
				tid: string;
				subject: string;
				activity?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_all_special_for_today_entry_special_today_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_entryspecial_by_sid_entry_special__sid__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				sid: number | null;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	root__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
}
