create table
    private.hours (
        created_at timestamp
        with
            time zone not null default now (),
            day text not null,
            hour integer not null,
            room text not null,
            teacher text not null,
            fullname text not null,
            consultation boolean not null default false,
            slimit bigint not null default 0,
            area_of_expertise text null,
            id bigint generated by default as identity not null,
            constraint hours_pkey primary key (id)
    );

create table
    private.special_indy (
        id bigint generated by default as identity not null,
        created_at timestamp
        with
            time zone not null default now (),
            teacher text not null,
            day text not null,
            hour integer not null,
            start_date date not null,
            end_date date not null,
            constraint special_indy_pkey primary key (id)
    );

create view
    private.current_special_indy as
select
    id,
    created_at,
    teacher,
    day,
    hour,
    start_date,
    end_date
from
    private.special_indy s
where
    CURRENT_DATE + 1 between start_date and end_date;

create view
    private.available_indy_hours as
select
    h.created_at,
    h.day,
    h.hour,
    h.room,
    h.teacher,
    h.fullname,
    h.consultation,
    h.slimit,
    h.area_of_expertise,
    h.id
from
    private.hours h
    left join private.current_special_indy s on h.teacher = s.teacher
    and h.day = s.day
    and h.hour = s.hour
where
    s.id is null;

create table
    private.subjects (
        subject text not null,
        created_at timestamp
        with
            time zone not null default now (),
            constraint subjects_pkey primary key (subject)
    );

create table
    private.booking_data (
        id bigint generated by default as identity not null,
        created_at timestamp
        with
            time zone not null default now (),
            teacher text not null,
            day text not null,
            hour integer not null,
            subject text not null,
            user_id uuid not null,
            activity text not null,
            priority smallint not null,
            constraint booking_data_pkey primary key (id),
            constraint booking_data_subject_fkey foreign KEY (subject) references private.subjects (subject) on update CASCADE on delete CASCADE,
            constraint booking_data_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
    );

create view
    private.indy_entry_candidates as
select
    b.id,
    b.created_at,
    b.teacher,
    b.day,
    b.hour,
    b.subject,
    b.user_id,
    b.activity,
    b.priority
from
    private.booking_data b
    join private.available_indy_hours a on b.day = a.day
    and b.hour = a.hour
    and b.teacher = a.teacher;

-- ============================================================
-- Schema access
-- ============================================================
grant usage on schema private to authenticated;

-- ============================================================
-- hours (reference data — authenticated users read-only)
-- ============================================================
alter table private.hours enable row level security;

create policy "hours: authenticated users can read"
    on private.hours for select
    to authenticated
    using (true);

grant select on private.hours to authenticated;

-- ============================================================
-- special_indy (reference data — authenticated users read-only)
-- ============================================================
alter table private.special_indy enable row level security;

create policy "special_indy: authenticated users can read"
    on private.special_indy for select
    to authenticated
    using (true);

grant select on private.special_indy to authenticated;

-- ============================================================
-- subjects (reference data — authenticated users read-only)
-- ============================================================
alter table private.subjects enable row level security;

create policy "subjects: authenticated users can read"
    on private.subjects for select
    to authenticated
    using (true);

grant select on private.subjects to authenticated;

-- ============================================================
-- booking_data (user data — own rows only)
-- ============================================================
alter table private.booking_data enable row level security;

create policy "booking_data: select own rows"
    on private.booking_data for select
    to authenticated
    using (auth.uid() = user_id);

create policy "booking_data: insert own rows"
    on private.booking_data for insert
    to authenticated
    with check (auth.uid() = user_id);

create policy "booking_data: update own rows"
    on private.booking_data for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

create policy "booking_data: delete own rows"
    on private.booking_data for delete
    to authenticated
    using (auth.uid() = user_id);

grant select, insert, update, delete on private.booking_data to authenticated;
